export const INTENTS = {
  CREATE_TABLE: "CREATE_TABLE",
  LIST_TABLES: "LIST_TABLES",
  DESCRIBE_TABLE: "DESCRIBE_TABLE",
  RENAME_TABLE: "RENAME_TABLE",
  DELETE_TABLE: "DELETE_TABLE",

  ADD_COLUMN: "ADD_COLUMN",
  DROP_COLUMN: "DROP_COLUMN",
  ALTER_COLUMN: "ALTER_COLUMN",

  CREATE_RECORD: "CREATE_RECORD",
  LIST_RECORDS: "LIST_RECORDS",
  GET_RECORD: "GET_RECORD",
  UPDATE_RECORD: "UPDATE_RECORD",
  DELETE_RECORD: "DELETE_RECORD",

  BULK_UPDATE_RECORDS: "BULK_UPDATE_RECORDS",
  BULK_DELETE_RECORDS: "BULK_DELETE_RECORDS",

  JOIN_QUERY: "JOIN_QUERY",
  JOIN_CREATE_TABLE: "JOIN_CREATE_TABLE",

  AGGREGATE_QUERY: "AGGREGATE_QUERY",
  AGGREGATE_CREATE_TABLE: "AGGREGATE_CREATE_TABLE",

  GRANT_TABLE_ACCESS: "GRANT_TABLE_ACCESS",
  REVOKE_TABLE_ACCESS: "REVOKE_TABLE_ACCESS",
  GRANT_TICKET_PERMISSION: "GRANT_TICKET_PERMISSION",
  REVOKE_TICKET_PERMISSION: "REVOKE_TICKET_PERMISSION",

  CREATE_TICKET: "CREATE_TICKET",
  UPDATE_TICKET_STATUS: "UPDATE_TICKET_STATUS",
  ADD_TICKET_NOTE: "ADD_TICKET_NOTE",

  UNKNOWN: "UNKNOWN",
};

export const DESTRUCTIVE_INTENTS = [
  INTENTS.DELETE_TABLE,
  INTENTS.DELETE_RECORD,
  INTENTS.BULK_DELETE_RECORDS,
];

// Every intent that mutates data. All of these
// require an explicit user confirmation before
// they are dispatched. Read intents are excluded
// on purpose - they always execute immediately.
export const WRITE_INTENTS = [
  INTENTS.CREATE_TABLE,
  INTENTS.RENAME_TABLE,
  INTENTS.DELETE_TABLE,

  INTENTS.ADD_COLUMN,
  INTENTS.DROP_COLUMN,
  INTENTS.ALTER_COLUMN,

  INTENTS.CREATE_RECORD,
  INTENTS.UPDATE_RECORD,
  INTENTS.DELETE_RECORD,

  INTENTS.BULK_UPDATE_RECORDS,
  INTENTS.BULK_DELETE_RECORDS,

  INTENTS.JOIN_CREATE_TABLE,
  INTENTS.AGGREGATE_CREATE_TABLE,

  INTENTS.GRANT_TABLE_ACCESS,
  INTENTS.REVOKE_TABLE_ACCESS,
  INTENTS.GRANT_TICKET_PERMISSION,
  INTENTS.REVOKE_TICKET_PERMISSION,

  INTENTS.CREATE_TICKET,
  INTENTS.UPDATE_TICKET_STATUS,
  INTENTS.ADD_TICKET_NOTE,
];

// Admin-only - grants/revokes another employee's access, never
// resolved against TableMetadata/columns like TABLE_INTENTS/
// RECORD_INTENTS are, so they're routed separately in the controller.
export const PERMISSION_INTENTS = [
  INTENTS.GRANT_TABLE_ACCESS,
  INTENTS.REVOKE_TABLE_ACCESS,
  INTENTS.GRANT_TICKET_PERMISSION,
  INTENTS.REVOKE_TICKET_PERMISSION,
];

// Tickets have their own dedicated model/service, never resolved
// against TableMetadata/columns like TABLE_INTENTS/RECORD_INTENTS are.
export const TICKET_INTENTS = [
  INTENTS.CREATE_TICKET,
  INTENTS.UPDATE_TICKET_STATUS,
  INTENTS.ADD_TICKET_NOTE,
];

// Schema-mutating intents (create/rename/delete a table, add/drop/alter
// a column, or persist a join/aggregate as a brand new table) are
// admin-only - employees get record-level CRUD on tables they've been
// granted access to, not control over which tables exist or their
// shape. Read-only DESCRIBE_TABLE/LIST_TABLES are NOT in this list -
// employees can still look at (their allowed) tables' schemas.
export const SCHEMA_WRITE_INTENTS = [
  INTENTS.CREATE_TABLE,
  INTENTS.RENAME_TABLE,
  INTENTS.DELETE_TABLE,
  INTENTS.ADD_COLUMN,
  INTENTS.DROP_COLUMN,
  INTENTS.ALTER_COLUMN,
  INTENTS.JOIN_CREATE_TABLE,
  INTENTS.AGGREGATE_CREATE_TABLE,
];

export const TABLE_INTENTS = [
  INTENTS.CREATE_TABLE,
  INTENTS.LIST_TABLES,
  INTENTS.DESCRIBE_TABLE,
  INTENTS.RENAME_TABLE,
  INTENTS.DELETE_TABLE,
  INTENTS.ADD_COLUMN,
  INTENTS.DROP_COLUMN,
  INTENTS.ALTER_COLUMN,
];

export const RECORD_INTENTS = [
  INTENTS.CREATE_RECORD,
  INTENTS.LIST_RECORDS,
  INTENTS.GET_RECORD,
  INTENTS.UPDATE_RECORD,
  INTENTS.DELETE_RECORD,
  INTENTS.BULK_UPDATE_RECORDS,
  INTENTS.BULK_DELETE_RECORDS,

  INTENTS.AGGREGATE_QUERY,
];
